### ISSUE TITLE
Getting error while pushing the app

### ISSUE THREAD

**Issue by sheo2020** [SAP-samples/cloud-sample-node-chat#9]
Hi,
I am getting the following error while pushing this app into my Enterprise SCP account:

For application 'chat': Routes cannot be mapped to destinations in different spaces
FAILED

Can you please help me to get this issue resolved.

regards,
sheo

**Comment by sheo2020** [comment]
here is the command detail I have used:

C:\Users\s1018579\OneDrive\Documents\Syngenta\SAP-Cloud-Platform\CloudFoundryApp\cloud-sample-node-chat>cf push
Pushing app chat to org prc.syngenta.com / space cf-space01 as sheo_shankar.choudhary@syngenta.com...
Applying manifest file C:\Users\s1018579\OneDrive\Documents\Syngenta\SAP-Cloud-Platform\CloudFoundryApp\cloud-sample-node-chat\manifest.yml...
For application 'chat': Routes cannot be mapped to destinations in different spaces
FAILED


Also when I have deployed this application through SAP SCP Cockpit, the application is getting crashed with following detail:


10 Sep 2020, 18:51:24 (GMT+05:30) | app.crash | chat | instance: df8837b2-41cc-40c8-6e17-bbcd, index: 0, cell_id: 814210d3-a82a-40f2-897e-93c24dbae0d7, exit_description: APP/PROC/WEB: Exited with status 254, reason: CRASHED |   |  
-- | -- | -- | -- | -- | --
  | 10 Sep 2020, 18:51:24 (GMT+05:30) | audit.app.process.crash | web | instance: df8837b2-41cc-40c8-6e17-bbcd, index: 0, cell_id: 814210d3-a82a-40f2-897e-93c24dbae0d7, reason: CRASHED, exit_description: APP/PROC/WEB: Exited with status 254, crash_count: 6, crash_timestamp: 1599744084041828000, version: 2c693bb0-385d-469d-859e-25711bf162fc

Can you please have alook into this and let me know the reason, if possible.

**Comment by navinkrishnan** [comment]
Hi @sheo2020 ,
Could be the reason, the route is already used in different space.
Can you try with different `host` or use the `random-route` when pushing the application ?

    cf push --random-route

**Comment by Mohanasunder** [comment]
@sheo2020  Did you got the resolution for this issue? I am also facing the.
